# Generated by Django 6.0.6 on 2026-06-30 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('register_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game_type', models.CharField(choices=[('word_puzzle', 'Word Puzzle'), ('mcq', 'Multiple Choice Questions'), ('fill_blanks', 'Fill in the Blanks'), ('match_following', 'Match the Following')], max_length=20)),
                ('instructions', models.TextField(help_text='How to play the game')),
                ('explanation', models.TextField(help_text='The concept/explanation behind the answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct_word', models.CharField(blank=True, max_length=100, null=True)),
                ('letters_override', models.CharField(blank=True, help_text='Comma-separated custom letters to show (optional)', max_length=200, null=True)),
                ('clue1', models.TextField(blank=True, null=True)),
                ('clue1_time', models.IntegerField(default=15, help_text='Time in seconds for Clue 1 to appear')),
                ('clue2', models.TextField(blank=True, null=True)),
                ('clue2_time', models.IntegerField(default=30, help_text='Time in seconds for Clue 2 to appear')),
                ('full_marks', models.IntegerField(default=10, help_text='Score before any clues appear')),
                ('reduced_marks_clue1', models.IntegerField(default=7, help_text='Score after Clue 1 appears')),
                ('min_marks_clue2', models.IntegerField(default=4, help_text='Score after Clue 2 appears')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game_core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FillBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text="Use double underscores '__' to represent the blank. E.g. 'The capital of France is __.'")),
                ('correct_answer', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_questions', to='game_core.game')),
            ],
        ),
        migrations.CreateModel(
            name='MatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(max_length=255)),
                ('right_item', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_items', to='game_core.game')),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='game_core.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('clues_used', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.IntegerField(help_text='Time taken in seconds')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='game_core.game')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='game_core.student')),
            ],
        ),
    ]
