# Generated by Django 6.0.6 on 2026-06-30 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='clue1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='clue1_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='clue2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='clue2_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='correct_word',
        ),
        migrations.RemoveField(
            model_name='game',
            name='full_marks',
        ),
        migrations.RemoveField(
            model_name='game',
            name='letters_override',
        ),
        migrations.RemoveField(
            model_name='game',
            name='min_marks_clue2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='reduced_marks_clue1',
        ),
        migrations.CreateModel(
            name='WordPuzzleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_word', models.CharField(max_length=100)),
                ('letters_override', models.CharField(blank=True, help_text='Comma-separated custom letters to show (optional)', max_length=200, null=True)),
                ('clue1', models.TextField()),
                ('clue1_time', models.IntegerField(default=15, help_text='Time in seconds for Clue 1 to appear')),
                ('clue2', models.TextField()),
                ('clue2_time', models.IntegerField(default=30, help_text='Time in seconds for Clue 2 to appear')),
                ('full_marks', models.IntegerField(default=10, help_text='Score before any clues appear')),
                ('reduced_marks_clue1', models.IntegerField(default=7, help_text='Score after Clue 1 appears')),
                ('min_marks_clue2', models.IntegerField(default=4, help_text='Score after Clue 2 appears')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_puzzles', to='game_core.game')),
            ],
        ),
    ]
