# Generated by Django 6.0.6 on 2026-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core', '0003_anonymousfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillblankquestion',
            name='clue',
            field=models.TextField(blank=True, help_text='Optional clue for this question', null=True),
        ),
    ]
