# Generated by Django 6.0.6 on 2026-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core', '0004_fillblankquestion_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether students can see and play this game.'),
        ),
    ]
