# Generated by Django 6.0.6 on 2026-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core', '0005_game_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
