# Generated by Django 6.0.6 on 2026-07-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core', '0006_student_password_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillblankquestion',
            name='clue1',
            field=models.TextField(blank=True, help_text='First clue for fill in blanks', null=True),
        ),
        migrations.AddField(
            model_name='fillblankquestion',
            name='clue2',
            field=models.TextField(blank=True, help_text='Second clue for fill in blanks', null=True),
        ),
        migrations.AddField(
            model_name='fillblankquestion',
            name='clue3',
            field=models.TextField(blank=True, help_text='Third clue for fill in blanks', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='clue1',
            field=models.TextField(blank=True, help_text='First overall clue for match game', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='clue2',
            field=models.TextField(blank=True, help_text='Second overall clue for match game', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='clue3',
            field=models.TextField(blank=True, help_text='Third overall clue for match game', null=True),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='clue1',
            field=models.TextField(blank=True, help_text='First clue for MCQ', null=True),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='clue2',
            field=models.TextField(blank=True, help_text='Second clue for MCQ', null=True),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='clue3',
            field=models.TextField(blank=True, help_text='Third clue for MCQ', null=True),
        ),
        migrations.AddField(
            model_name='wordpuzzlequestion',
            name='clue3',
            field=models.TextField(blank=True, help_text='Third clue for word puzzle', null=True),
        ),
    ]
