# Generated by Django 6.0.6 on 2026-07-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core', '0007_fillblankquestion_clue1_fillblankquestion_clue2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGamePlayPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_attempts', models.IntegerField(default=1, help_text='Number of attempts allowed for this student on this game')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_permissions', to='game_core.game')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_permissions', to='game_core.student')),
            ],
            options={
                'unique_together': {('student', 'game')},
            },
        ),
    ]
