# Generated by Django 6.0.6 on 2026-07-07 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core', '0009_pdfnote_studentmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_feedback_enabled', models.BooleanField(default=True, help_text='Allow students to submit anonymous suggestions.')),
                ('replays_enabled', models.BooleanField(default=True, help_text='Allow students to replay completed games if unlocked.')),
                ('games_enabled', models.BooleanField(default=True, help_text='Allow students to play games on the platform.')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
