# Generated by Django 6.0.6 on 2026-07-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core', '0011_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfeedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
