# Generated by Django 6.0.6 on 2026-07-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core', '0013_game_approval_status_game_created_by_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='max_marks',
            field=models.IntegerField(default=100),
        ),
    ]
